# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 마경환
title: Java 백엔드 엔지니어
email: ghma1213@gmail.com
website: https://github.com/ghma1213

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  ghma1213
stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요. Java & Spring, AWS 기반의 4년차 백엔드 개발자입니다.


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 사회평론
        link: https://sapyoung.com/
        # link_text: boringcompany.com
        sub_title: 웹 개발자
        caption: July 2021 - Present
        quote: >
          영어교육 전문 출판 브랜드 Bricks
        description: | # this will include new lines to allow paragraphs
          - 사내 프로젝트 개발 및 레거시 시스템 리팩토링
          - Spring boot, JPA, MySql 환경에서의 개발 경험

      - layout: left
        title: 갈렙ABC
        link: https://www.calebabc.com/
        sub_title: 웹 개발자
        caption: September 2019 - June 2021
        quote: >
          병원대상 관리회계(원가, 성과), 통계분석 컨설팅/솔루션
        description: | # this will include new lines to allow paragraphs
          - 사내 프로젝트 개발 및 기존 솔루션 유지보수
          - Spring boot, MyBatis, Oracle 환경에서의 개발 경험
          - Go, SQLite, PostgreSQL 환경에서의 개발 경험

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 중앙대학교
        caption: 2015 - 2017
        sub_title: 화학신소재공학
        quote: >
          중앙대학교(中央大學校, Chung-Ang University)는 서울특별시 동작구와 경기도 안성시에 위치해 있는 대한민국의 사립대학이다.
        description: | # this will include new lines to allow paragraphs
          - 화학신소재공학이란 원료에 물리적/화학적 변화를 가하여 부가가치를 높이거나 원하는 물성을 갖는 소재를 개발하기 위한 개별 공정을 탐구하는 학문이다. 

      - layout: left
        title: 경기과학기술대학교
        caption: 2009 - 2014
        sub_title: 자동차과
        quote: >
          경기과학기술대학교(京畿科學技術大學校, Gyeonggi University of Science and Technology)는 경기도 시흥시의 전문대학이다.
        description: | # this will include new lines to allow paragraphs
          - 자동차과는 국가의 기간산업으로 기계, 전기, 전자, 통신 등 산업 전반에 핵심이 되는 중요한 산업이다. 
          - 서부산업단지를 거점으로 자동차 산업 발전에 맞추어 필요한 인재를 양성하는 학과로서 자동차 정비, 자동차 부품설계, 그리고 친환경 전기자동차에 대한 우수한 전문기술인을 양성하는 것을 목표로 한다.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
